#!/usr/bin/env python3
"""Generate every icon in the app from one source image.

    pip install Pillow numpy
    python android/scripts/generate-icons.py

`android/artwork/icon-source.png` is the only artwork in the project. Nothing
here redraws or restyles it — the script trims the transparent margin, then
rescales that same image into each slot Android needs:

  * mipmap-*/ic_launcher.png        legacy launcher icon
  * mipmap-*/ic_launcher_round.png  identical file; round-icon launchers get the
                                    same artwork rather than a cropped variant
  * mipmap-*/ic_launcher_foreground.png  adaptive foreground, API 26+
  * drawable-nodpi/anydown_logo.png the in-app logo

Adaptive icons are the one place Android forces a second layer: the launcher
masks the foreground to its own shape and paints a background behind it. That
background is set to the artwork's own tile colour (written to icon_colors.xml),
so on a circular launcher the mask cuts a dark circle out of a dark tile and the
artwork is what you see.
"""

from pathlib import Path

import numpy as np
from PIL import Image

LEGACY_SIZES = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}
FOREGROUND_SIZES = {
    "mipmap-mdpi": 108,
    "mipmap-hdpi": 162,
    "mipmap-xhdpi": 216,
    "mipmap-xxhdpi": 324,
    "mipmap-xxxhdpi": 432,
}

# Adaptive icons reserve the centre 66 of 108 units. Anything outside can be
# cropped by the launcher mask.
SAFE_ZONE = 66 / 108

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "artwork" / "icon-source.png"
RES_DIR = ROOT / "app" / "src" / "main" / "res"
LOGO_SIZE = 512


def load_artwork() -> Image.Image:
    """Trim the transparent (or white) margin and pad back to a square."""
    if not SOURCE.exists():
        raise SystemExit(f"missing source artwork: {SOURCE}")

    image = Image.open(SOURCE).convert("RGBA")
    pixels = np.asarray(image).astype(int)
    alpha = pixels[..., 3]

    if alpha.max() > 0 and alpha.min() == 0:
        visible = alpha > 8
    else:
        # Fully opaque source: fall back to trimming a near-white border.
        visible = pixels[..., :3].sum(axis=2) < 700

    ys, xs = np.where(visible)
    if len(xs) == 0:
        raise SystemExit("source artwork appears to be empty")

    tile = image.crop((int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1))

    side = max(tile.size)
    square = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    square.paste(tile, ((side - tile.width) // 2, (side - tile.height) // 2), tile)
    return square


def tile_colour(tile: Image.Image) -> tuple:
    """Median colour of the artwork's opaque dark area."""
    pixels = np.asarray(tile).astype(int)
    opaque = pixels[pixels[..., 3] > 200]
    if len(opaque) == 0:
        return (18, 18, 20)
    dark = opaque[opaque[..., :3].sum(axis=1) < 400]
    source = dark if len(dark) else opaque
    return tuple(int(v) for v in np.median(source[:, :3], axis=0))


def main() -> None:
    artwork = load_artwork()
    backdrop = tile_colour(artwork)
    print(f"artwork {artwork.size}, tile colour #{'%02X%02X%02X' % backdrop}")

    written = 0

    for folder, size in LEGACY_SIZES.items():
        target = RES_DIR / folder
        target.mkdir(parents=True, exist_ok=True)
        scaled = artwork.resize((size, size), Image.LANCZOS)
        # Same file for both: a round-icon launcher shows the artwork, not a
        # differently-cropped version of it.
        scaled.save(target / "ic_launcher.png", "PNG", optimize=True)
        scaled.save(target / "ic_launcher_round.png", "PNG", optimize=True)
        written += 2

    for folder, size in FOREGROUND_SIZES.items():
        target = RES_DIR / folder
        target.mkdir(parents=True, exist_ok=True)
        art = int(size * SAFE_ZONE)
        layer = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        scaled = artwork.resize((art, art), Image.LANCZOS)
        offset = (size - art) // 2
        layer.paste(scaled, (offset, offset), scaled)
        layer.save(target / "ic_launcher_foreground.png", "PNG", optimize=True)
        written += 1

    logo_dir = RES_DIR / "drawable-nodpi"
    logo_dir.mkdir(parents=True, exist_ok=True)
    artwork.resize((LOGO_SIZE, LOGO_SIZE), Image.LANCZOS).save(
        logo_dir / "anydown_logo.png", "PNG", optimize=True
    )
    written += 1

    colours = RES_DIR / "values" / "icon_colors.xml"
    colours.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by android/scripts/generate-icons.py from the source\n"
        "     artwork. Do not edit by hand. -->\n"
        "<resources>\n"
        f'    <color name="icon_background">#FF{"%02X%02X%02X" % backdrop}</color>\n'
        "</resources>\n",
        encoding="utf-8",
    )

    print(f"wrote {written} image files and {colours.name}")


if __name__ == "__main__":
    main()
